name: repathy
description: "Il futuro della riabilitazione"
publish_to: 'none'
version: 2.0.7

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  # Media (Image, Video)
  video_player: ^2.8.2
  path_provider: ^2.1.2
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.7
  image: ^4.1.7

  # PDF
  flutter_pdfview: ^1.4.0 # used for viewing PDFs
  printing: ^5.13.4 # used for printing PDFs
  pdf: ^3.11.1 # used for generating PDFs

  # Payment
  in_app_purchase: ^3.2.1
  in_app_purchase_storekit: ^0.3.21 # IOS
  in_app_purchase_android: ^0.4.0 # Android

  # Controllers / Providers
  riverpod_annotation: ^2.5.3
  flutter_riverpod: ^2.5.3

  # Models / Immutability
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Database / Storage
  firebase_storage: ^12.3.3
  cloud_firestore: ^5.4.4

  # Notifications
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.0

  # Analytics
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3  

  # Security
  flutter_dotenv: ^5.1.0
  firebase_app_check: ^0.3.1+3

  # QR Code
  pretty_qr_code: ^3.3.0
  # mobile_scanner: ^6.0.2

  # Utility
  collection: ^1.18.0 
  uuid: ^4.5.1

  # Navigation
  go_router: ^14.3.0
  url_launcher: ^6.3.1

  # Authentication
  firebase_auth: ^5.3.1

  # Local Storage
  shared_preferences: ^2.3.2

  # App Initialization
  another_flutter_splash_screen: ^1.2.1

  # Firebase
  firebase_core: ^3.12.1

  # HTTP Requests
  http: ^1.2.2

  # Logo
  flutter_launcher_icons: ^0.14.3

  # Privacy
  app_tracking_transparency: ^2.0.6+1

  # Translations
  intl: any   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.2
  freezed: ^3.0.4
  json_serializable: ^6.8.0
  mockito: ^5.4.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/pain/
    - assets/image/
    - assets/logo/
    - assets/fonts/
    - assets/pdf_fonts/
    - assets/profile/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-VariableFont_wght.ttf
        - asset: assets/fonts/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit-Black.ttf
          weight: 900
     
    - family: Roboto
      fonts:
         - asset: assets/pdf_fonts/Roboto-Thin.ttf
           weight: 100
         - asset: assets/pdf_fonts/Roboto-ExtraLight.ttf
           weight: 200  
         - asset: assets/pdf_fonts/Roboto-Light.ttf
           weight: 300
         - asset: assets/pdf_fonts/Roboto-Regular.ttf
           weight: 400
         - asset: assets/pdf_fonts/Roboto-Medium.ttf
           weight: 500
         - asset: assets/pdf_fonts/Roboto-SemiBold.ttf
           weight: 600
         - asset: assets/pdf_fonts/Roboto-Bold.ttf
           weight: 700
         - asset: assets/pdf_fonts/Roboto-ExtraBold.ttf
           weight: 800  
         - asset: assets/pdf_fonts/Roboto-Black.ttf
           weight: 900                         